CREATE DATABASE CHANNELLING;

USE CHANNELLING;

create TABLE PATIENT (NIC VARCHAR(15) NOT NULL, FIRST_NAME VARCHAR(20) NOT NULL,LAST_NAME VARCHAR(20) NOT NULL,
 DATE_OF_BIRTH VARCHAR(20) NOT NULL, DIABETES  TINYINT(1) NOT NULL, BLOOD_PRESSURE   TINYINT(1) NOT NULL,
CHOLESTEROL TINYINT(1) NOT NULL, ALLERGY TINYINT(1) NOT NULL,NOTES VARCHAR(40), CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT(3), PRIMARY KEY (NIC))ENGINE=InnoDB;

insert into PATIENT  values( '123456V', 'Nimal', 'Blasuriya', '95-05-12', 1,0,0,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);
insert into PATIENT  values( '321565V', 'VVVV', 'AAA', '95-05-12', 1,0,1,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);