CREATE DATABASE CHANNELLING;

USE CHANNELLING;

create TABLE PATIENT (NIC VARCHAR(15) NOT NULL, FIRST_NAME VARCHAR(20) NOT NULL,LAST_NAME VARCHAR(20) NOT NULL,
 DATE_OF_BIRTH VARCHAR(20) NOT NULL, DIABETES  TINYINT(1) NOT NULL, BLOOD_PRESSURE   TINYINT(1) NOT NULL,
CHOLESTEROL TINYINT(1) NOT NULL, ALLERGY TINYINT(1) NOT NULL,NOTES VARCHAR(40), CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT(3), PRIMARY KEY (NIC))ENGINE=InnoDB;

insert into PATIENT  values( '123456V', 'Nimal', 'Blasuriya', '95-05-12', 1,0,0,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);
insert into PATIENT  values( '321565V', 'VVVV', 'AAA', '95-05-12', 1,0,1,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);

CREATE TABLE T_QUEUE (
  QUEUE_ID INT NOT NULL auto_increment,
  DOCTOR_ID VARCHAR(30) NOT NULL,
  QUE_STATUS VARCHAR(10) NOT NULL,
  PATIENT_ID INT NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT(3),
  PRIMARY KEY (QUEUE_ID)
)ENGINE=InnoDB;

INSERT INTO T_QUEUE VALUES (1, 'DOC123', 'ACTIVE', '5',CURRENT_TIMESTAMP, NULL , 0);

CREATE TABLE QUEUE_PATIENT (
  QUEUE_PATIENT_ID INT NOT NULL auto_increment,
  PATIENT_NIC VARCHAR(30) NOT NULL,
  QUEUE_ID INT NOT NULL,
  QUEUE_PATIENT_STATUS VARCHAR(10) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT(3),
  PRIMARY KEY (QUEUE_ID),
  FOREIGN KEY (QUEUE_PATIENT_ID) REFERENCES T_QUEUE(QUEUE_ID) ON DELETE CASCADE
)ENGINE=InnoDB;

INSERT INTO QUEUE_PATIENT VALUES (1, '123456V', 1, 'WAITING', CURRENT_TIMESTAMP, NULL , 0);
