create TABLE PATIENT (
NIC VARCHAR(15) PRIMARY KEY,
FIRST_NAME VARCHAR(20) ,
LAST_NAME VARCHAR(20) ,
DATE_OF_BIRTH VARCHAR(20) ,
DIABETES  INT(1) ,
BLOOD_PRESSURE INT(1) ,
CHOLESTEROL INT(1) ,
ALLERGY INT(1) ,
NOTES VARCHAR(40),
CREATED_DATE TIMESTAMP,
LAST_MODIFIED_DATE TIMESTAMP ,
VERSION INT(3)
);

insert into PATIENT  values( '123456V', 'Nimal', 'Blasuriya', '95-05-12', 1,0,0,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);
insert into PATIENT  values( '321565V', 'VVVV', 'AAA', '95-05-12', 1,0,1,0,'Nothing', CURRENT_TIMESTAMP, NULL ,0);
